# Generated by Django 4.2.7 on 2026-07-01 19:13

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProviderConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "slug",
                    models.CharField(
                        help_text='Provider identifier matching the adapter slug (e.g. "demo", "pragmatic").',
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("display_name", models.CharField(max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("MAINTENANCE", "Maintenance"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "credentials",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Provider API credentials (api_key, secret, endpoint, …).",
                    ),
                ),
                (
                    "settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Adapter-specific operational settings.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "provider_configs",
                "ordering": ["slug"],
            },
        ),
        migrations.CreateModel(
            name="ProviderGameCatalog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("provider_game_id", models.CharField(max_length=256)),
                ("name", models.CharField(max_length=256)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("slots", "Slots"),
                            ("table", "Table Games"),
                            ("live", "Live Casino"),
                            ("instant_win", "Instant Win"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=32,
                    ),
                ),
                ("thumbnail_url", models.URLField(blank=True, max_length=1024)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "min_bet",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.10"),
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "max_bet",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("10000.00"),
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "rtp",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("96.00"),
                        help_text="Return-to-player percentage.",
                        max_digits=5,
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
                ("extra", models.JSONField(blank=True, default=dict)),
                ("synced_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="games",
                        to="providers.providerconfig",
                    ),
                ),
            ],
            options={
                "db_table": "provider_game_catalog",
                "ordering": ["provider", "name"],
            },
        ),
        migrations.CreateModel(
            name="ProviderGameSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("session_token", models.CharField(max_length=512, unique=True)),
                ("launch_url", models.URLField(max_length=2048)),
                ("currency", models.CharField(default="INR", max_length=3)),
                (
                    "mode",
                    models.CharField(
                        choices=[("real", "Real"), ("demo", "Demo")],
                        default="real",
                        max_length=8,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("EXPIRED", "Expired"),
                            ("CLOSED", "Closed"),
                        ],
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("extra", models.JSONField(blank=True, default=dict)),
                (
                    "game",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sessions",
                        to="providers.providergamecatalog",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sessions",
                        to="providers.providerconfig",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="provider_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "provider_game_sessions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProviderRound",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("round_id", models.CharField(max_length=128, unique=True)),
                ("provider_round_id", models.CharField(blank=True, max_length=256)),
                (
                    "bet_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "payout",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("currency", models.CharField(default="INR", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("WON", "Won"),
                            ("LOST", "Lost"),
                            ("PUSH", "Push"),
                            ("SETTLED", "Settled"),
                            ("REFUNDED", "Refunded"),
                            ("VOIDED", "Voided"),
                            ("ERROR", "Error"),
                        ],
                        default="PENDING",
                        max_length=12,
                    ),
                ),
                ("bet_ledger_entry_id", models.CharField(blank=True, max_length=64)),
                ("payout_ledger_entry_id", models.CharField(blank=True, max_length=64)),
                ("raw_bet_response", models.JSONField(blank=True, default=dict)),
                ("raw_settle_response", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("settled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "game",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rounds",
                        to="providers.providergamecatalog",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rounds",
                        to="providers.providerconfig",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rounds",
                        to="providers.providergamesession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="provider_rounds",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "provider_rounds",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="providerconfig",
            index=models.Index(fields=["slug"], name="provider_co_slug_19a3dd_idx"),
        ),
        migrations.AddIndex(
            model_name="providerconfig",
            index=models.Index(fields=["status"], name="provider_co_status_39f7ed_idx"),
        ),
        migrations.AddIndex(
            model_name="providerround",
            index=models.Index(
                fields=["user", "-created_at"], name="provider_ro_user_id_6c4d2e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="providerround",
            index=models.Index(
                fields=["provider", "status"], name="provider_ro_provide_61ea97_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="providerround",
            index=models.Index(
                fields=["round_id"], name="provider_ro_round_i_0c24c3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="providerround",
            index=models.Index(
                fields=["provider_round_id"], name="provider_ro_provide_2423af_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="providerround",
            index=models.Index(
                fields=["-created_at"], name="provider_ro_created_01aef0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="providergamesession",
            index=models.Index(
                fields=["user", "-created_at"], name="provider_ga_user_id_f2c3ad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="providergamesession",
            index=models.Index(
                fields=["provider", "status"], name="provider_ga_provide_0e6857_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="providergamesession",
            index=models.Index(
                fields=["session_token"], name="provider_ga_session_00cd6d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="providergamesession",
            index=models.Index(
                fields=["-created_at"], name="provider_ga_created_fd6c51_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="providergamecatalog",
            index=models.Index(
                fields=["provider", "is_active"], name="provider_ga_provide_dce0e6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="providergamecatalog",
            index=models.Index(
                fields=["category"], name="provider_ga_categor_c79dbb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="providergamecatalog",
            index=models.Index(
                fields=["-created_at"], name="provider_ga_created_4f5a41_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="providergamecatalog",
            unique_together={("provider", "provider_game_id")},
        ),
    ]
