# Generated by Django 4.2.7 on 2026-07-01 02:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="ledgerentry",
            new_name="ledger_entr_wallet__b56567_idx",
            old_name="ledger_wallet_created_idx",
        ),
        migrations.RenameIndex(
            model_name="ledgerentry",
            new_name="ledger_entr_entry_t_8d6d0c_idx",
            old_name="ledger_type_created_idx",
        ),
        migrations.RenameIndex(
            model_name="ledgerentry",
            new_name="ledger_entr_referen_1ef0a5_idx",
            old_name="ledger_ref_idx",
        ),
        migrations.RenameIndex(
            model_name="ledgerentry",
            new_name="ledger_entr_idempot_5bfbbc_idx",
            old_name="ledger_idemp_idx",
        ),
        migrations.RenameIndex(
            model_name="ledgerentry",
            new_name="ledger_entr_created_c070e4_idx",
            old_name="ledger_created_idx",
        ),
        migrations.RenameIndex(
            model_name="wallet",
            new_name="wallets_user_id_9fb6cf_idx",
            old_name="wallets_user_idx",
        ),
        migrations.RenameIndex(
            model_name="wallet",
            new_name="wallets_status_5720bd_idx",
            old_name="wallets_status_idx",
        ),
        migrations.AlterField(
            model_name="ledgerentry",
            name="actor",
            field=models.CharField(
                blank=True,
                help_text="User or system that initiated this entry.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="ledgerentry",
            name="idempotency_key",
            field=models.CharField(
                blank=True,
                help_text="Prevents duplicate ledger effects for the same business event.",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="ledgerentry",
            name="reference_id",
            field=models.CharField(
                blank=True, help_text="ID of the originating entity.", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="ledgerentry",
            name="reference_type",
            field=models.CharField(
                blank=True,
                help_text="Type of the originating entity (e.g. payment, game_room, etc.)",
                max_length=50,
            ),
        ),
    ]
